Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,11 +27,14 @@ jobs:
       - name: Install dependencies
         run: flutter pub get
 
-      - name: Enable Gradle Daemon
-        run: echo "org.gradle.daemon=true" >> android/gradle.properties
+      - name: Clean previous builds
+        run: flutter clean
 
       - name: Build APK
-        run: flutter build apk --release
+        run: flutter build apk --release --verbose
+
+      - name: List Output Directory
+        run: ls -la build/app/outputs/flutter-apk/ || echo "Directory not found"
 
       - name: Upload APK Artifact
         uses: actions/upload-artifact@v4
